services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 8090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prometheus/prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST={$GF_SMTP_HOST}
      - GF_SMTP_USER={$GF_SMTP_USER}
      - GF_SMTP_PASSWORD={$GF_SMTP_PASSWORD}
      - GF_SMTP_FROM_ADDRESS={$GF_SMTP_FROM_ADDRESS}
      - GF_SMTP_FROM_NAME={$GF_SMTP_FROM_NAME}
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
      - ./grafana/data:/var/lib/grafana
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    restart: unless-stopped
    user: root
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/conf/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ./alertmanager/data:/var/lib/alertmanager
volumes:
  prom_data:
